"""Instrument a disposable MIZ with one hash-bound terrain-probe script."""

from __future__ import annotations

import hashlib
import io
import os
import zipfile
from pathlib import Path
from typing import Any

from .archive import inspect_miz
from .lua import LuaField, LuaTable, parse_lua_bytes
from .lua_write import dump_lua_assignment
from .mission import analyse_miz
from .terrain_probe import (
    MAX_REQUEST_BYTES,
    MAX_SCRIPT_BYTES,
    _load_request,
    _read_regular_file,
    _write_output,
)


MAX_MIZ_BYTES = 512 * 1024 * 1024
FIXED_ZIP_TIME = (1980, 1, 1, 0, 0, 0)
MISSION_MEMBER = "mission"
MAP_RESOURCE_MEMBER = "l10n/DEFAULT/mapResource"
RESOURCE_DIRECTORY = "l10n/DEFAULT"
SCRIPT_PREFIX = b"-- Generated by DCSMizzer."


def instrument_terrain_probe_miz(
    mission_path: Path,
    request_path: Path,
    script_path: Path,
    output_path: Path,
    *,
    force: bool = False,
) -> dict[str, Any]:
    """Create a verified disposable derivative; never alter the source MIZ."""

    mission_input = Path(mission_path)
    request_input = Path(request_path)
    script_input = Path(script_path)
    output = Path(output_path)
    _reject_output_alias(
        output,
        (mission_input, request_input, script_input),
    )
    request, request_payload = _load_request(request_input)
    if len(request_payload) > MAX_REQUEST_BYTES:
        raise ValueError("terrain probe request exceeds the byte limit")
    request_sha256 = hashlib.sha256(request_payload).hexdigest()
    script = _read_regular_file(script_input, MAX_SCRIPT_BYTES)
    if not script.startswith(SCRIPT_PREFIX):
        raise ValueError("script is not a generated DCSMizzer terrain probe")
    if request_sha256.encode("ascii") not in script:
        raise ValueError("terrain probe script is not bound to the request")

    source_payload = _read_regular_file(mission_input, MAX_MIZ_BYTES)
    source_stream = io.BytesIO(source_payload)
    source_archive = inspect_miz(source_stream, verify_crc=True)
    if (
        not source_archive.valid_zip
        or not source_archive.safe
        or source_archive.crc_status != "passed"
    ):
        raise ValueError("source MIZ did not pass ZIP safety and CRC checks")
    source_stream.seek(0)
    source_analysis = analyse_miz(source_stream)
    if not source_analysis.parse_valid or not source_analysis.theatre:
        raise ValueError("source MIZ core tables could not be parsed")
    if request["terrain"].casefold() != source_analysis.theatre.casefold():
        raise ValueError("terrain probe request does not match the mission theatre")

    script_sha256 = hashlib.sha256(script).hexdigest()
    resource_key = f"ResKey_DCSMizzerTerrainProbe_{script_sha256[:16]}"
    resource_name = f"DCSMizzerTerrainProbe-{script_sha256[:16]}.lua"
    resource_member = f"{RESOURCE_DIRECTORY}/{resource_name}"
    instrumented_payload, trigger_index = _instrument_archive(
        source_payload,
        script,
        resource_key=resource_key,
        resource_name=resource_name,
        resource_member=resource_member,
    )
    _verify_instrumented_archive(
        instrumented_payload,
        source_analysis=source_analysis,
        script=script,
        resource_key=resource_key,
        resource_member=resource_member,
        trigger_index=trigger_index,
    )
    _write_output(output, instrumented_payload, force=force)
    return {
        "schema": "dcsmizzer.terrain-probe-instrumentation/v1",
        "authority": "verified_disposable_derivative_of_exact_source_miz",
        "dcs_started": False,
        "source": {
            "name": mission_input.name,
            "size_bytes": len(source_payload),
            "sha256": hashlib.sha256(source_payload).hexdigest(),
            "theatre": source_analysis.theatre,
            "archive_valid": True,
            "parse_valid": True,
        },
        "probe": {
            "request_sha256": request_sha256,
            "script_sha256": script_sha256,
            "resource_key": resource_key,
            "resource_member": resource_member,
            "trigger_index": trigger_index,
        },
        "output": {
            "name": output.name,
            "size_bytes": len(instrumented_payload),
            "sha256": hashlib.sha256(instrumented_payload).hexdigest(),
        },
        "validation": {
            "source_archive_safe_and_crc_passed": True,
            "source_core_tables_parsed": True,
            "request_hash_matched": True,
            "theatre_matched": True,
            "probe_resource_exact": True,
            "instrumented_archive_safe_and_crc_passed": True,
            "instrumented_core_tables_parsed": True,
            "mission_entities_preserved": True,
            "mission_human_slots_preserved": True,
            "startup_trigger_binding_exact": True,
            "runtime_test_performed": False,
        },
        "limitations": [
            "The output is a local disposable derivative for validation and "
            "must not be redistributed when the source mission is copyrighted.",
            "Instrumentation proves archive and trigger wiring only; terrain "
            "evidence exists only after the exact output is run in DCS and its "
            "hash-bound log markers are extracted.",
            "The source mission is parsed and canonically reserialized, so its "
            "mission/mapResource bytes are intentionally not byte-identical.",
        ],
    }


def _instrument_archive(
    source_payload: bytes,
    script: bytes,
    *,
    resource_key: str,
    resource_name: str,
    resource_member: str,
) -> tuple[bytes, int]:
    output = io.BytesIO()
    with zipfile.ZipFile(io.BytesIO(source_payload), "r") as source:
        names = source.namelist()
        if MISSION_MEMBER not in names or MAP_RESOURCE_MEMBER not in names:
            raise ValueError("source MIZ is missing required core members")
        if resource_member.casefold() in {name.casefold() for name in names}:
            raise ValueError("terrain probe resource member already exists")
        mission = _assignment_table(source.read(MISSION_MEMBER), "mission")
        map_resource = _assignment_table(
            source.read(MAP_RESOURCE_MEMBER),
            "mapResource",
        )
        if map_resource.has(resource_key):
            raise ValueError("terrain probe resource key already exists")
        if any(
            isinstance(field.value, str)
            and field.value.casefold() == resource_name.casefold()
            for field in map_resource.fields
        ):
            raise ValueError("terrain probe resource filename already exists")
        mission, trigger_index = _add_probe_trigger(mission, resource_key)
        map_resource = _replace_field(map_resource, resource_key, resource_name)
        replacements = {
            MISSION_MEMBER: dump_lua_assignment("mission", mission),
            MAP_RESOURCE_MEMBER: dump_lua_assignment("mapResource", map_resource),
        }
        payloads: list[tuple[str, bytes]] = []
        for name in sorted(names):
            payloads.append((name, replacements.get(name, source.read(name))))
        payloads.append((resource_member, script))
        with zipfile.ZipFile(
            output,
            "w",
            compression=zipfile.ZIP_DEFLATED,
            compresslevel=9,
        ) as target:
            for name, payload in sorted(payloads, key=lambda item: item[0]):
                info = zipfile.ZipInfo(name, FIXED_ZIP_TIME)
                info.compress_type = zipfile.ZIP_DEFLATED
                info.create_system = 3
                info.external_attr = 0o100600 << 16
                target.writestr(
                    info,
                    payload,
                    compress_type=zipfile.ZIP_DEFLATED,
                    compresslevel=9,
                )
    return output.getvalue(), trigger_index


def _add_probe_trigger(mission: LuaTable, resource_key: str) -> tuple[LuaTable, int]:
    rules = mission.get("trigrules")
    trig = mission.get("trig")
    if not isinstance(rules, LuaTable) or not isinstance(trig, LuaTable):
        raise ValueError("source mission trigger tables are missing")
    conditions = trig.get("conditions")
    actions = trig.get("actions")
    startup = trig.get("funcStartup")
    if (
        not isinstance(conditions, LuaTable)
        or not isinstance(actions, LuaTable)
        or not isinstance(startup, LuaTable)
    ):
        raise ValueError("source mission startup trigger tables are missing")
    used = {
        int(field.key)
        for table in (rules, conditions, actions, startup)
        for field in table.numeric_items()
        if isinstance(field.key, int) and not isinstance(field.key, bool)
    }
    trigger_index = max(used, default=0) + 1
    action_record = LuaTable(
        (
            LuaField("zone", ""),
            LuaField("meters", 1000),
            LuaField("file", resource_key),
            LuaField("predicate", "a_do_script_file"),
        )
    )
    rule = LuaTable(
        (
            LuaField("rules", LuaTable(())),
            LuaField("eventlist", ""),
            LuaField("comment", "DCSMizzer terrain probe"),
            LuaField("actions", LuaTable((LuaField(1, action_record),))),
            LuaField("predicate", "triggerStart"),
            LuaField("colorItem", "0x008080ff"),
        )
    )
    rules = _append_numeric(rules, trigger_index, rule)
    conditions = _append_numeric(conditions, trigger_index, "return(true)")
    actions = _append_numeric(
        actions,
        trigger_index,
        f'a_do_script_file(getValueResourceByKey("{resource_key}"));',
    )
    startup = _append_numeric(
        startup,
        trigger_index,
        "if mission.trig.conditions[%d]() then mission.trig.actions[%d]() end"
        % (trigger_index, trigger_index),
    )
    trig = _replace_field(trig, "conditions", conditions)
    trig = _replace_field(trig, "actions", actions)
    trig = _replace_field(trig, "funcStartup", startup)
    mission = _replace_field(mission, "trigrules", rules)
    mission = _replace_field(mission, "trig", trig)
    return mission, trigger_index


def _verify_instrumented_archive(
    payload: bytes,
    *,
    source_analysis: Any,
    script: bytes,
    resource_key: str,
    resource_member: str,
    trigger_index: int,
) -> None:
    stream = io.BytesIO(payload)
    archive = inspect_miz(stream, verify_crc=True)
    if not archive.valid_zip or not archive.safe or archive.crc_status != "passed":
        raise ValueError("instrumented MIZ did not pass ZIP safety and CRC checks")
    stream.seek(0)
    analysis = analyse_miz(stream)
    if not analysis.parse_valid or analysis.theatre != source_analysis.theatre:
        raise ValueError("instrumented MIZ core tables did not parse consistently")
    if (
        analysis.stats.groups != source_analysis.stats.groups
        or analysis.stats.units != source_analysis.stats.units
    ):
        raise ValueError("instrumentation changed mission entity counts")
    if analysis.stats.human_slots != source_analysis.stats.human_slots:
        raise ValueError("instrumentation changed mission human slots")
    with zipfile.ZipFile(io.BytesIO(payload), "r") as archive_file:
        if archive_file.read(resource_member) != script:
            raise ValueError("instrumented terrain probe resource does not match")
        mission = _assignment_table(archive_file.read(MISSION_MEMBER), "mission")
        map_resource = _assignment_table(
            archive_file.read(MAP_RESOURCE_MEMBER),
            "mapResource",
        )
    rules = mission.get("trigrules")
    trig = mission.get("trig")
    if not isinstance(rules, LuaTable) or not isinstance(trig, LuaTable):
        raise ValueError("instrumented trigger tables are missing")
    conditions = trig.get("conditions")
    actions = trig.get("actions")
    startup = trig.get("funcStartup")
    if not all(isinstance(value, LuaTable) for value in (conditions, actions, startup)):
        raise ValueError("instrumented startup trigger tables are missing")
    rule = rules.get(trigger_index)
    action_table = rule.get("actions") if isinstance(rule, LuaTable) else None
    action = action_table.get(1) if isinstance(action_table, LuaTable) else None
    expected_action = f'a_do_script_file(getValueResourceByKey("{resource_key}"));'
    expected_startup = (
        f"if mission.trig.conditions[{trigger_index}]() then "
        f"mission.trig.actions[{trigger_index}]() end"
    )
    if (
        not isinstance(action, LuaTable)
        or not isinstance(conditions, LuaTable)
        or not isinstance(actions, LuaTable)
        or not isinstance(startup, LuaTable)
        or not isinstance(rule, LuaTable)
        or rule.get("predicate") != "triggerStart"
        or action.get("predicate") != "a_do_script_file"
        or action.get("file") != resource_key
        or conditions.get(trigger_index) != "return(true)"
        or actions.get(trigger_index) != expected_action
        or startup.get(trigger_index) != expected_startup
        or map_resource.get(resource_key) != Path(resource_member).name
    ):
        raise ValueError("instrumented trigger/resource binding is invalid")


def _reject_output_alias(output: Path, inputs: tuple[Path, ...]) -> None:
    """Prevent force replacement of any exact input, including hard links."""

    output_resolved = output.resolve(strict=False)
    for input_path in inputs:
        try:
            input_resolved = input_path.resolve(strict=True)
        except OSError as error:
            raise ValueError("terrain probe input path cannot be resolved") from error
        if output_resolved == input_resolved:
            raise ValueError("terrain probe output must differ from every input")
        if output.exists():
            try:
                if os.path.samefile(output, input_path):
                    raise ValueError(
                        "terrain probe output must not alias an input file"
                    )
            except OSError as error:
                raise ValueError(
                    "terrain probe output identity cannot be checked safely"
                ) from error


def _assignment_table(payload: bytes, name: str) -> LuaTable:
    parsed = parse_lua_bytes(payload)
    value = parsed.document.get(name)
    if value is None and isinstance(parsed.document.returned, LuaTable):
        value = parsed.document.returned
    if not isinstance(value, LuaTable):
        raise ValueError(f"{name} is not a data-only Lua table")
    return value


def _replace_field(table: LuaTable, key: str, value: Any) -> LuaTable:
    return LuaTable(
        tuple(field for field in table.fields if field.key != key)
        + (LuaField(key, value),)
    )


def _append_numeric(table: LuaTable, key: int, value: Any) -> LuaTable:
    if table.has(key):
        raise ValueError("terrain probe trigger index collides with source mission")
    return LuaTable(table.fields + (LuaField(key, value),))
